name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build-APK:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Flet
        run: pip install flet==0.19.0

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.9'

      - name: Update Dart SDK
        run: flutter upgrade

      - name: Build APK
        run: |
          flet build apk
          mv ./build/apk/app-release.apk ./build/apk/grassbag.apk

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./build/apk/grassbag.apk
  
  build-IPA:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Flet
        run: pip install flet==0.19.0

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.9'

      - name: Update Dart SDK
        run: flutter upgrade

      - name: Build IPA
        run: flet build ipa

      - name: Convert xcarchive to ipa
        run: |
          cd ./build/ipa/Runner.xcarchive/Products
          mv Applications Payload
          zip -r Payload.zip Payload
          mv Payload.zip grassbag.ipa
          pwd

      - name: Upload ipa
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: /Users/runner/work/grassbag/grassbag/build/ipa/Runner.xcarchive/Products/grassbag.ipa

  build-APK-hua:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Flet
        run: pip install flet==0.19.0

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.9'

      - name: Update Dart SDK
        run: flutter upgrade

      - name: Build APK
        run: |
          flet build apk --project PROJECT_NAME letsgo --org ORG_NAME com.tencent
          mv ./build/apk/app-release.apk ./build/apk/grassbag-hua.apk

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: apk-hua
          path: ./build/apk/grassbag-hua.apk
  
  build-IPA-hua:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Flet
        run: pip install flet==0.19.0

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.9'

      - name: Update Dart SDK
        run: flutter upgrade

      - name: Build IPA
        run: flet build ipa --project PROJECT_NAME letsgo --org ORG_NAME com.tencent

      - name: Convert xcarchive to ipa
        run: |
          cd ./build/ipa/Runner.xcarchive/Products
          mv Applications Payload
          zip -r Payload.zip Payload
          mv Payload.zip grassbag-hua.ipa
          pwd

      - name: Upload ipa
        uses: actions/upload-artifact@v4
        with:
          name: ipa-hua
          path: /Users/runner/work/grassbag/grassbag/build/ipa/Runner.xcarchive/Products/grassbag-hua.ipa
