name: Build IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Flet
        run: pip install flet

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'

      - name: Update Dart SDK
        run: flutter upgrade

      - name: Build IPA
        run: flet build ipa

      - name: Export ipa
        run: xcodebuild -exportArchive -archivePath ./build/ipa/Runner.xcarchive -exportPath ./build/ipa/grassbag.ipa -exportOptionsPlist ExportOptions.plist CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Zip build folder
        run: zip -r build.zip build

      - name: Upload build folder
        uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: build.zip

      - name: Upload ipa
        uses: actions/upload-artifact@v2
        with:
          name: grassbag.ipa
          path: ./build/ipa/grassbag.ipa
