name: Build IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Flet
        run: pip install flet

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.9'

      - name: Update Dart SDK
        run: flutter upgrade

      - name: Build IPA
        run: flet build ipa

      - name: Convert xcarchive to ipa
        run: |
          cd ./build/ipa/Runner.xcarchive/Products
          mv Applications Payload
          zip -r Payload.zip Payload
          mv Payload.zip grassbag.ipa

      - name: Upload ipa
        uses: actions/upload-artifact@v2
        with:
          name: grassbag.ipa
          path: ./grassbag.ipa
