name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev python3-dev
  
      - name: Install cffi
        run: pip install cffi
  
      - name: Install cryptography
        run: pip install cryptography

      - name: Install Flet
        run: pip install flet pycryptodome

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.9'

      - name: Update Dart SDK
        run: flutter upgrade

      - name: Upgrade pip
        run: python -m pip install --upgrade pip


      - name: Build APK
        run: flet build apk

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: grassbag.apk
          path: ./build/apk/app-release.apk
