name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Flet
        run: pip install flet

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'

      - name: Update Dart SDK
        run: flutter upgrade

      - name: Change package name
        run: |
          sed -i 's/package="com.example.grassbag"/package="com.tencent.letsgo"/g' android/app/src/main/AndroidManifest.xml
          sed -i 's/applicationId "com.example.grassbag"/applicationId "com.tencent.letsgo"/g' android/app/build.gradle

      - name: Zip build folder
        run: zip -r build.zip build

      - name: Upload build folder
        uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: build.zip
